# Generated by Django 4.1.7 on 2024-04-17 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=library_app.models.get_datetime, null=True, validators=[library_app.models.check_created], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=library_app.models.get_datetime, null=True, validators=[library_app.models.check_modified], verbose_name='modified')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='money')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': '"library"."client"',
            },
        ),
        migrations.CreateModel(
            name='BookClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=library_app.models.get_datetime, null=True, validators=[library_app.models.check_created], verbose_name='created')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'relationship book client',
                'verbose_name_plural': 'relationships book client',
                'db_table': '"library"."book_client"',
            },
        ),
    ]
