# Generated by Django 4.1.7 on 2024-04-24 08:07

from django.db import migrations, models
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_client_bookclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[library_app.models.check_positive], verbose_name='price'),
        ),
        migrations.AddField(
            model_name='client',
            name='books',
            field=models.ManyToManyField(through='library_app.BookClient', to='library_app.book', verbose_name='books'),
        ),
        migrations.AlterField(
            model_name='client',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[library_app.models.check_positive], verbose_name='money'),
        ),
        migrations.AlterUniqueTogether(
            name='bookclient',
            unique_together={('book', 'client')},
        ),
    ]
